name: API Validation
on: [push, pull_request]

jobs:
  validate-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run unit tests
        run: |
          python -m pytest tests/ -v
        continue-on-error: true

      - name: Validate example API
        run: |
          python src/main.py validate specs/example_spec.yaml \
            --test-data examples/test_data.json \
            --output-format html
        continue-on-error: true

      - name: Quick validate PokéAPI
        run: |
          python src/main.py validate specs/pokeapi_spec.yaml \
            --test-data examples/pokeapi_test_data.json \
            --output-format html
        continue-on-error: true

      - name: Upload reports
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: validation-reports
          path: reports/
          retention-days: 30
